#!/usr/bin/env node
// Generate mock data for testing from OpenAPI schema types
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outputPath = resolve(__dirname, '../generated/mocks.ts')

// Auto-generated mock factory stubs
const mockContent = `// AUTO-GENERATED by contracts/scripts/generate-mocks.js
// DO NOT EDIT — regenerated from openapi.yaml on each \`bun run codegen\`

/**
 * Mock data factories for consumer testing.
 * These produce minimal valid shapes for each schema type.
 *
 * Usage:
 *   import { mockProductSummary, mockCart } from '@ecom/contracts/mocks'
 *   const product = mockProductSummary({ name: 'Custom' })
 */

let counter = 0
const uuid = () => \`00000000-0000-4000-8000-\${String(++counter).padStart(12, '0')}\`
const timestamp = () => new Date().toISOString()
const slug = (prefix: string) => \`\${prefix}-\${counter}\`

// ── Money ────────────────────────────────────────────────────────────
export function mockMoney(overrides: Partial<{ amount: number; currency: 'VND' }> = {}) {
  return { amount: 100_000, currency: 'VND' as const, ...overrides }
}

// ── Media ────────────────────────────────────────────────────────────
export function mockMediaRef(overrides: Record<string, unknown> = {}) {
  return {
    id: uuid(),
    url: 'https://cdn.example.com/image.jpg',
    altText: 'Product image',
    width: 800,
    height: 600,
    ...overrides,
  }
}

// ── Variant ──────────────────────────────────────────────────────────
export function mockVariant(overrides: Record<string, unknown> = {}) {
  return {
    id: uuid(),
    size: 'M',
    color: 'Black',
    skuCode: \`SKU-\${counter}\`,
    priceVnd: 350_000,
    availability: 'in_stock' as const,
    ...overrides,
  }
}

// ── Product Summary ──────────────────────────────────────────────────
export function mockProductSummary(overrides: Record<string, unknown> = {}) {
  return {
    id: uuid(),
    name: 'Sample Product',
    slug: slug('sample-product'),
    excerpt: 'A sample product description',
    coverMedia: mockMediaRef(),
    priceRange: { min: 200_000, max: 500_000, currency: 'VND' as const },
    ...overrides,
  }
}

// ── Product Detail ───────────────────────────────────────────────────
export function mockProductDetail(overrides: Record<string, unknown> = {}) {
  return {
    id: uuid(),
    name: 'Sample Product',
    slug: slug('sample-product'),
    description: '<p>Full product description</p>',
    variants: [mockVariant()],
    complianceInfo: { careInstructions: ['Machine wash cold'], materialComposition: '100% Cotton', countryOfOrigin: 'Vietnam' },
    media: [mockMediaRef()],
    priceRange: { min: 200_000, max: 500_000, currency: 'VND' as const },
    ...overrides,
  }
}

// ── Post ─────────────────────────────────────────────────────────────
export function mockPostSummary(overrides: Record<string, unknown> = {}) {
  return {
    id: uuid(),
    title: 'Sample Post',
    slug: slug('sample-post'),
    excerpt: 'A sample post excerpt',
    coverMedia: mockMediaRef(),
    publishedAt: timestamp(),
    ...overrides,
  }
}

export function mockPostDetail(overrides: Record<string, unknown> = {}) {
  return {
    ...mockPostSummary(),
    body: '<p>Full post body content</p>',
    attachedMedia: [],
    ...overrides,
  }
}

// ── Cart ─────────────────────────────────────────────────────────────
export function mockCart(overrides: Record<string, unknown> = {}) {
  return {
    items: [{ variantId: uuid(), quantity: 1, variant: mockVariant() }],
    updatedAt: timestamp(),
    ...overrides,
  }
}

// ── Quote ────────────────────────────────────────────────────────────
export function mockQuote(overrides: Record<string, unknown> = {}) {
  return {
    quoteId: uuid(),
    expiresAt: timestamp(),
    serverTime: timestamp(),
    itemSubtotal: 350_000,
    shipping: 30_000,
    discount: 0,
    tax: 0,
    grandTotal: 380_000,
    currency: 'VND' as const,
    ...overrides,
  }
}

// ── Order ────────────────────────────────────────────────────────────
export function mockOrderSummary(overrides: Record<string, unknown> = {}) {
  return {
    id: uuid(),
    orderNumber: \`ORD-\${counter}\`,
    status: 'pending' as const,
    grandTotal: 380_000,
    createdAt: timestamp(),
    ...overrides,
  }
}

// ── ProblemDetails ───────────────────────────────────────────────────
export function mockProblemDetails(overrides: Record<string, unknown> = {}) {
  return {
    type: 'about:blank',
    title: 'Bad Request',
    status: 400,
    code: 'validation_error' as const,
    detail: 'Validation failed',
    ...overrides,
  }
}

// ── Challenge ────────────────────────────────────────────────────────
export function mockChallengeAccepted(overrides: Record<string, unknown> = {}) {
  return {
    expiresAt: timestamp(),
    resendAfter: timestamp(),
    serverTime: timestamp(),
    ...overrides,
  }
}
`

writeFileSync(outputPath, mockContent, 'utf-8')
console.log(`Mock factories written to generated/mocks.ts`)
