#!/bin/bash
# Setup GitHub labels for phase tracking
# Usage: ./scripts/setup-labels.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

cd "$PROJECT_ROOT"

echo -e "${BLUE}🏷️ Setting up GitHub labels...${NC}"
echo ""

# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo -e "${RED}✗ GitHub CLI (gh) is not installed${NC}"
    echo "Install from: https://cli.github.com/"
    exit 1
fi

# Define labels
declare -A LABELS=(
    ["phase-0"]="0075ca|Phase 0: Contract Foundation|OpenAPI spec, schemas, mocks"
    ["phase-1"]="0e8a16|Phase 1: DB & DevOps|Database, CI/CD, infrastructure"
    ["phase-2"]="a2eeef|Phase 2: Features|Business logic implementation"
    ["auto-generated"]="ededed|Auto-generated by CI/CD|Automated commits and PRs"
    ["phase-complete"]="0e8a16|Phase Complete|All tasks in phase are done"
    ["ready-for-review"]="fbca04|Ready for Review|Awaiting human review"
    ["bug"]="d73a4a|Bug|Something isn't working"
    ["feature"]="a2eeef|Feature|New functionality"
    ["enhancement"]="a2eeef|Enhancement|Improvement to existing feature"
    ["documentation"]="0075ca|Documentation|Docs only"
    ["dependencies"]="0366d6|Dependencies|Pull requests that update a dependency file"
    ["security"]="ee0701|Security|Security related"
)

CREATED=0
SKIPPED=0

for label in "${!LABELS[@]}"; do
    IFS='|' read -r color description notes <<< "${LABELS[$label]}"

    # Check if label exists
    if gh label list --search "$label" 2>/dev/null | grep -q "^$label"; then
        echo -e "  ${YELLOW}⚠ $label already exists, skipping${NC}"
        SKIPPED=$((SKIPPED + 1))
    else
        # Create label
        if gh label create "$label" --color "$color" --description "$description" 2>/dev/null; then
            echo -e "  ${GREEN}✓ Created: $label${NC}"
            CREATED=$((CREATED + 1))
        else
            echo -e "  ${RED}✗ Failed to create: $label${NC}"
        fi
    fi
done

echo ""
echo -e "${GREEN}✅ Labels setup complete!${NC}"
echo "  Created: $CREATED"
echo "  Skipped: $SKIPPED"
echo ""
echo "Phase labels ready:"
echo "  - phase-0: Contract Foundation"
echo "  - phase-1: DB & DevOps"
echo "  - phase-2: Features"
